flask_proje_one/controllers/admin.py
from flask import Blueprint, request, render_template, session, jsonify
from libraries.db_helper import get_db
from libraries.app_functions import login_required
from libraries.exceptions import ValidationException
from libraries.forms import NewPostForm, EditPostForm

admin_bp = Blueprint('admin', __name__, url_prefix='/admin')

@admin_bp.route("/")
@login_required
def dashboard():
    return render_template("admin_dashboard.html")

@admin_bp.route("/post_new",methods=["GET","POST"])
@login_required
def post_new():
    data = {"status": "success", "error_message": ""}

    new_post_form = NewPostForm()

    if new_post_form.is_submitted():
        if new_post_form.validate():
            try:
                post_title = new_post_form.post_title.data
                post_summary = new_post_form.post_summary.data
                post_content = new_post_form.post_content.data

                db = get_db()
                cr = db.cursor()

                sql = "INSERT INTO posts(post_title,post_summary,post_content,user_id) VALUES(?,?,?,?)"
                cr.execute(sql, (post_title, post_summary, post_content, session["user_id"]))
                db.commit()
            except ValidationException as e:
                data["status"] = "error"
                data["error_message"] = str(e)
            except Exception as e:
                data["status"] = "error"
                data["error_message"] = str(e)
            finally:
                if data["status"] == "error":
                    errorHtml = render_template("errors_messages.html", form=new_post_form, data=data)
                    data["error_message"] = errorHtml
        elif request.method=="POST":
            data["status"] = "error"
            data["error_message"] = render_template("errors_messages.html", form=new_post_form, data=data)

        return jsonify(data)


    return render_template("admin_post_new.html", new_post_form=new_post_form, data=data)



@admin_bp.route("/post_edit/<post_id>",methods=["GET","POST"])
@login_required
def post_edit(post_id):
    data = {"status": "success", "error_message": ""}

    db = get_db()
    cr = db.cursor()

    post_edit_form = EditPostForm()
    if post_edit_form.is_submitted():
        if post_edit_form.validate():
            try:
                post_title = post_edit_form.post_title.data
                post_summary = post_edit_form.post_summary.data
                post_content = post_edit_form.post_content.data

                sql = "UPDATE posts SET post_title=?, post_summary=?, post_content=? WHERE post_id=?"
                cr.execute(sql, (post_title, post_summary, post_content, post_id))
                db.commit()
            except ValidationException as e:
                data["status"] = "error"
                data["error_message"] = str(e)
            except Exception as e:
                data["status"] = "error"
                data["error_message"] = "Bilinmeyen bir hata oluştu"
            finally:
                if data["status"] == "error":
                    errorHtml = render_template("errors_messages.html", form=post_edit_form, data=data)
                    data["error_message"] = errorHtml
        else:
            data["status"] = "error"
            data["error_message"] = render_template("errors_messages.html", form=post_edit_form, data=data)

        return jsonify(data)

    sql = "SELECT * FROM posts WHERE post_id=?"
    cr.execute(sql,(post_id,))
    post_item = cr.fetchone()

    return render_template("admin_post_edit.html", post_item=post_item, post_edit_form=post_edit_form)


@admin_bp.route("/posts")
@login_required
def admin_posts():
    db = get_db()
    cr = db.cursor()

    sql = "SELECT * FROM posts JOIN users ON posts.user_id=users.user_id WHERE posts.user_id=?"
    cr.execute(sql, (str(session["user_id"]),))
    post_items = cr.fetchall()


    return render_template("admin_posts.html", post_items=post_items)

flask_proje_one/controllers/auth.py
from flask import Blueprint, render_template, session, redirect, url_for, jsonify
from flask_babel import gettext as _

from libraries.app_functions import hash_password
from libraries.db_helper import get_db
from libraries.exceptions import ValidationException
from libraries.forms import LoginForm, RegisterForm

auth_bp = Blueprint('auth', __name__, url_prefix='/auth')



@auth_bp.route("/register", methods=["GET","POST"])
def register_user():
    data = {"status": "success", "error_message" : ""}

    register_form = RegisterForm()
    if register_form.is_submitted():
        if register_form.validate():
            try:
                db = get_db()
                cr = db.cursor()

                hashedPassword = hash_password(register_form.password.data)

                sql = "INSERT INTO users(username,password,full_name) VALUES(?,?,?)"
                cr.execute(sql, (register_form.username.data, hashedPassword, register_form.full_name.data))
                db.commit()

            except ValidationException as e:
                data["status"] = "error"
                data["error_message"] = str(e)
            except Exception as e:
                data["status"] = "error"
                data["error_message"] = _("Bilinmeyen bir hata oluştu")
            finally:
                if data["status"] == "error":
                    errorHtml = render_template("errors_messages.html", form=register_form, data=data)
                    data["error_message"] = errorHtml
        else:
            data["status"] = "error"
            data["error_message"] = render_template("errors_messages.html", form=register_form, data=data)

        return jsonify(data)

    return render_template("register.html",data=data,register_form=register_form)



@auth_bp.route("/login", methods=["GET","POST"])
def login():
    data = {"status" : "success", "error_message": ""}

    loginForm = LoginForm()
    if loginForm.is_submitted():
        if loginForm.validate():
            try:
                db = get_db()
                cr = db.cursor()

                hashedPassword = hash_password(loginForm.password.data)
                cr.execute("SELECT * FROM users WHERE username=? AND password=?", (loginForm.username.data, hashedPassword))
                user = cr.fetchone()

                if not user:
                    raise ValidationException(_("Lütfen bilgileri eksiksiz giriniz"))

                session["username"] = user["username"]
                session["full_name"] = user["full_name"]
                session["user_id"] = user["user_id"]

            except ValidationException as e:
                data["status"] = "error"
                data["error_message"] = str(e)
            except Exception as e:
                data["status"] = "error"
                data["error_message"] = _("Bilinmeyen bir hata oluştu")
            finally:
                if data["status"]=="error":
                    errorHtml = render_template("errors_messages.html", form=loginForm, data=data)
                    data["error_message"] = errorHtml
        else:
            data["status"] = "error"
            data["error_message"] = render_template("errors_messages.html", form=loginForm, data=data)

        return jsonify(data)

    return render_template("login.html", loginForm=loginForm, data=data)




@auth_bp.route("/logout")
def logout():
    session.pop("username", None)
    session.pop("full_name", None)
    session.pop("user_id", None)
    return redirect(url_for("website.posts"))

flask_proje_one/controllers/website.py
from flask import Blueprint, render_template, session, redirect, url_for, jsonify, request, abort
from flask.views import View, MethodView

from libraries.app_functions import login_required
from libraries.db_helper import get_db

website_bp = Blueprint('website', __name__, url_prefix='/')

@website_bp.route("/")
def posts():
    db = get_db()
    cr = db.cursor()

    params = []
    sql = "SELECT * FROM posts LEFT JOIN users ON posts.user_id=users.user_id"

    q = request.args.get("query")
    if q:
        sql += " WHERE post_content LIKE ? OR post_title LIKE ? OR post_summary LIKE ?"
        params.append('%'+q+'%')
        params.append('%'+q+'%')
        params.append('%'+q+'%')

    cr.execute(sql,tuple(params))

    post_items = cr.fetchall()
    #print(post_items)
    return render_template("posts.html", post_items=post_items)


@website_bp.route("/post/<id>")
def show_post(id):
    db = get_db()
    cr = db.cursor()
    cr.execute("SELECT * FROM posts LEFT JOIN users ON posts.user_id=users.user_id WHERE post_id=?", (id,))
    post_item = cr.fetchone()

    if not post_item:
        abort(404)

    return render_template("show_post.html", post_item=post_item)

class ShowUsers(View):
    methods = ['GET', 'POST']

    def dispatch_request(self):
        db = get_db()
        cr = db.cursor()
        sql = "SELECT * FROM users"
        cr.execute(sql)
        user_items = cr.fetchall()

        return render_template('users.html',user_items=user_items)

# x = login_required(ShowUsers.as_view('users'))
website_bp.add_url_rule('/users/', view_func=ShowUsers.as_view('users'))

flask_proje_one/templates/admin_dashboard.html
{% extends "admin_layout.html" %}

{% block content %}

    <div class="page-wrapper p-5">
        {{ _("""
            Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
            Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
        """) }}
    </div>

{% endblock %}

flask_proje_one/templates/admin_layout.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for("static", filename="app.css") }}">

    <title>{% block title %}{% endblock %}</title>
</head>
<body>

<div class="container mt-5 mb-4">

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{{ url_for("website.posts") }}" target="_blank">
            <img src="http://www.serkandaglioglu.com/themes/serkandaglioglu/img/logo.png" id="logo"/>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="{{ url_for("admin.dashboard") }}">{{ _("Pano") }}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for("admin.post_new") }}">{{ _("Yazı Ekle") }}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for("admin.admin_posts") }}">{{ _("Yazılar") }}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for("auth.logout") }}">{{ _("Çıkış") }}</a>
                </li>
            </ul>

            <ul class="navbar-nav">
                <li class="nav-item">
                    <a href="#" class="nav-link">{{ _("Hoşgeldin %(username)s",username=session["full_name"]) }}</a>
                </li>
            </ul>
        </div>
    </nav>
</div>


<div class="container">
    {% block content %}{% endblock %}
</div>



<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

<!-- Include Editor style. -->
<link href="https://cdn.jsdelivr.net/npm/froala-editor@latest/css/froala_editor.pkgd.min.css" rel="stylesheet" type="text/css" />

<!-- Include Editor JS files. -->
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/froala-editor@latest/js/froala_editor.pkgd.min.js"></script>

<!-- Initialize the editor. -->

<script>
    function successMessageHtml(message) {
        return "<div class='alert alert-success'>"+message+"</div>"
    }
</script>
{% block script %}{% endblock %}

</body>
</html>

flask_proje_one/templates/admin_post_edit.html
{% extends "admin_layout.html" %}

{% block title %}{{ _("Yazı Düzenle") }}{% endblock %}

{% block content %}

    <div class="page-wrapper p-5">
        <h1>{{ _("Yazı Düzenle") }}</h1>

        <form action="{{ url_for("admin.post_edit", post_id=post_item["post_id"]) }}" method="post" id="post-edit-form">

            {{ post_edit_form.csrf_token }}

            <div class="form-group">
                <label for="post_title">{{ _("Başlık") }}</label>
                <input type="text" name="post_title" class="form-control" id="post_title"
                    value="{{ post_item["post_title"] }}">
            </div>

            <div class="form-group">
                <label for="post_summary">{{ _("Kısa Açıklama") }}</label>
                <textarea name="post_summary" class="form-control" id="post_summary" rows="3"
                    >{{ post_item["post_summary"] }}</textarea>
            </div>

            <div class="form-group">
                <label for="post_content">{{ _("İçerik") }}</label>
                <textarea name="post_content" class="form-control" id="post_content" rows="10"
                    >{{ post_item["post_content"] }}</textarea>
            </div>

            <hr>

            <button type="submit" class="btn btn-primary">{{ _("Kaydet") }}</button>
        </form>


        <div class="info-messages"></div>

    </div>

{% endblock %}

{% block script %}

    <script>
    $(function () {

        new FroalaEditor('#post_content');

        var formObj = $("#post-edit-form");
        formObj.on("submit",function (e) {

            var formData = formObj.serializeArray();
            $.ajax({
                type : "POST",
                url : formObj.attr("action"),
                data : formData,
                dataType : "json",
                success : function (data) {
                    if (data.status==="error"){
                        $(".info-messages").html(data.error_message);
                        return;
                    }

                    $("#btn-post-submit").attr("disabled",true)
                    $(".info-messages").html(successMessageHtml("{{ _("Post başarıyla düzendi.") }}"));
                }
            })

            return false;
        });


    })
    </script>

{% endblock %}

flask_proje_one/templates/admin_post_new.html
{% extends "admin_layout.html" %}

{% block content %}

    <div class="page-wrapper p-5">
        <h1>{{ _("Yazı Ekle") }}</h1>


        <form action="{{ url_for("admin.post_new") }}" method="post" id="new-post-form">
            {{ new_post_form.csrf_token }}

            <div class="form-group">
                <label for="post_title">{{ _("Başlık") }}</label>
                <input type="text" name="post_title" class="form-control" id="post_title">
            </div>

            <div class="form-group">
                <label for="post_summary">{{ _("Kısa Açıklama") }}</label>
                <textarea name="post_summary" class="form-control" id="post_summary" rows="3"></textarea>
            </div>

            <div class="form-group">
                <label for="post_content">{{ _("İçerik") }}</label>
                <textarea name="post_content" class="form-control" id="post_content" rows="10"></textarea>
            </div>

            <hr>

            <button type="submit" class="btn btn-primary" id="btn-post-submit">{{ _("Kaydet") }}</button>
        </form>


        <div class="info-messages"></div>

    </div>

{% endblock %}


{% block script %}

    <script>

    $(function () {

        new FroalaEditor('#post_content');

        var formObj = $("#new-post-form")
        formObj.on("submit",function (e) {

            try{
                var formData = formObj.serializeArray();
                $.ajax({
                    type    : "POST",
                    url     : formObj.attr("action"),
                    data    : formData,
                    dataType : "json",
                    success : function (data) {
                        if (data.status==="error"){
                            $(".info-messages").html(data.error_message);
                            return;
                        }

                        $("#btn-post-submit").attr("disabled",true)
                        $(".info-messages").html(successMessageHtml("{{ _("Post başarıyla kaydedildi.Postlar sayfasına yönlendiriliyorsunuz...") }}"));

                        setTimeout(function(){
                            window.location.href = "{{ url_for("admin.admin_posts") }}";
                        }, 2000);
                    }
                })

            }catch (e) {
                console.log(e)
            }

            return false;
        })
    })

    </script>

{% endblock %}

flask_proje_one/templates/admin_posts.html
{% extends "admin_layout.html" %}

{% block content %}

    <div class="page-wrapper">

        <table class="table table-striped">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">{{ _("Başlık") }}</th>
                <th scope="col">{{ _("Açıklama") }}</th>
                <th scope="col">{{ _("İşlemler") }}</th>
            </tr>
            </thead>
            <tbody>

            {% for post in post_items %}
                <tr>
                    <td>{{ post["post_id"] }}</td>
                    <td style="width:200px;">{{ post["post_title"] }}</td>
                    <td>{{ post["post_summary"] }}</td>
                    <td>
                        <a href="{{ url_for("admin.post_edit",post_id=post["post_id"]) }}" class="btn btn-sm btn-primary">{{ _("Düzenle") }}</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>


    </div>

{% endblock %}

flask_proje_one/templates/base_layout.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for("static", filename="app.css") }}">

    <title>{% block title %}{% endblock %}</title>
</head>
<body>

<div class="container mt-5 mb-4">
    <div class="row">
        <div class="col">
            <img src="http://www.serkandaglioglu.com/themes/serkandaglioglu/img/logo.png" id="logo"/>
            <a href="{{ url_for("website.posts") }}">Serkan Dağlıoğlu</a>
        </div>
        <div class="col">


            {% if "username" in session %}
                <a href="{{ url_for("admin.dashboard") }}" class="float-right">{{ _("Yönetici") }}</a>
            {% else %}
                <a href="{{ url_for("auth.login") }}" class="float-right btn btn-success">{{ _("Giriş") }}</a>
                <a href="{{ url_for("auth.register_user") }}" class="mr-2 float-right btn btn-warning">{{ _("Kayıt Ol") }}</a>
            {% endif %}


            <div class="dropdown float-right mr-2">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {{ _("Dil Seçin") }}
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <a class="dropdown-item" href="{{ url_for("change_lang",lang="tr") }}">{{ _("Türkçe") }}</a>
                    <a class="dropdown-item" href="{{ url_for("change_lang",lang="en") }}">{{ _("İngilizce") }}</a>
                </div>
            </div>


            {#<a href="#" class="btn btn-primary float-right">
                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-menu-button-wide-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M14 7H2a1 1 0 0 0-1 1v5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V8a1 1 0 0 0-1-1zM2 6a2 2 0 0 0-2 2v5a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2H2z"/>
                    <path fill-rule="evenodd" d="M15 11H1v-1h14v1zM2 12.5a.5.5 0 0 1 .5-.5h6a.5.5 0 0 1 0 1h-6a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5zM1.5 0A1.5 1.5 0 0 0 0 1.5v2A1.5 1.5 0 0 0 1.5 5h13A1.5 1.5 0 0 0 16 3.5v-2A1.5 1.5 0 0 0 14.5 0h-13zm1 2a.5.5 0 0 0 0 1h3a.5.5 0 0 0 0-1h-3zm9.927.427l.396.396a.25.25 0 0 0 .354 0l.396-.396A.25.25 0 0 0 13.396 2h-.792a.25.25 0 0 0-.177.427z"/>
                </svg>
            </a>#}
        </div>
    </div>
</div>


<div class="container">
    {% block content %}{% endblock %}
</div>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
{#<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>#}
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>


<script>
    function successMessageHtml(message) {
        return "<div class='alert alert-success'>" + message + "</div>"
    }
</script>

{% block script %}{% endblock %}

</body>
</html>

flask_proje_one/templates/login.html
{% extends "base_layout.html" %}

{% block content %}

    <div class="page-wrapper p-5">
        <h1>{{ _("Giriş") }}</h1>

        <div id="info-messages"></div>

        <form action="{{ url_for("auth.login") }}" method="post" id="login-form">
            {{ loginForm.csrf_token }}
            <div class="form-group">
                <label for="exampleInputEmail1">{{ _("Kullanıcı Adı") }}</label>
                <input type="text" name="username" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">{{ _("Şifre") }}</label>
                <input type="password" name="password" class="form-control" id="exampleInputPassword1">
            </div>
            <button type="submit" class="btn btn-primary" id="btn-login">{{ _("Giriş Yap") }}</button>
        </form>
    </div>

{% endblock %}


{% block script %}

    <script>

    $(function () {
        var formObj = $("#login-form");

        formObj.on("submit", function () {

            try{
                var formData = formObj.serializeArray();
                $.ajax({
                    type: "POST",
                    url: formObj.attr("action"),
                    data: formData,
                    dataJson: "json",
                    success: function (data) {
                        if (data.status==="error"){
                            $("#info-messages").html(data.error_message)
                            return;
                        }

                        $("#btn-login").attr("disabled",true)
                        $("#info-messages").html(successMessageHtml("{{ _("Giriş başarılı. Ana sayfaya yönlendiriliyorsunuz...") }}"));

                        setTimeout(function(){
                            window.location.href = "{{ url_for("admin.dashboard") }}";
                        }, 2000);
                    }
                });
            }catch (e) {
                console.log(e);
            }

            return false;
        });


    })
    </script>

{% endblock %}

flask_proje_one/templates/posts.html
{% extends "base_layout.html" %}

{% block title %}{{ _("Yazılar") }}{% endblock %}

{% block content %}

    <form action="{{ url_for("website.posts") }}" class="form-inline">
            <div class="form-group mr-3 mb-2">
                <input type="text" name="query" class="form-control" placeholder="{{ _("arama yap...") }}">
            </div>
            <button type="submit" class="btn btn-primary mb-2">{{ _("Ara") }}</button>
    </form>

    {% if post_items|length<1 %}
        <div class="alert alert-info">{{ _("Sonuç bulunamadı") }}</div>
    {% endif %}

    <div class="posts">
        {% for post in post_items %}
            <div class="card mb-2">
                <div class="card-body">
                    <h5 class="card-title">{{ post["post_title"] }}</h5>
                    <p>
                        <small>{{ _("Yazar") }} : <i>{{ post["full_name"] }}</i></small>
                    </p>
                    <p class="card-text">
                        {{ post["post_summary"] }}
                    </p>
                    <a href="{{ url_for("website.show_post", id=post["post_id"]) }}" class="card-link">{{ _("Görüntüle") }}</a>
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock %}

flask_proje_one/templates/register.html
{% extends "base_layout.html" %}

{% block content %}

    <div class="page-wrapper p-5">
        <h1>{{ _("Kayıt Ol") }}</h1>

        <form action="{{ url_for("auth.register_user") }}" method="post" id="register-form">
            {{ register_form.csrf_token }}
            <div class="form-group">
                <label for="input-full_name">{{ _("Full Name") }}</label>
                <input type="text" name="full_name" class="form-control" id="input-full_name">
            </div>

            <div class="form-group">
                <label for="exampleInputEmail1">{{ _("Kullanıcı Adı") }}</label>
                <input type="text" name="username" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">{{ _("Şifre") }}</label>
                <input type="password" name="password" class="form-control" id="exampleInputPassword1">
            </div>

            <div class="form-group">
                <label for="exampleInputPassword2">{{ _("Şifre Kontrol") }}</label>
                <input type="password" name="password_confirm" class="form-control" id="exampleInputPassword2">
            </div>
            <button type="submit" class="btn btn-primary" id="btn-register">{{ _("Kayıt Ol") }}</button>
        </form>

        <div id="info-messages"></div>

    </div>

{% endblock %}


{% block script %}

    <script>

    $(function () {
        var formObj = $("#register-form");

        formObj.on("submit", function () {

            try{
                var formData = formObj.serializeArray();
                $.ajax({
                    type: "POST",
                    url: formObj.attr("action"),
                    data: formData,
                    dataJson: "json",
                    success: function (data) {
                        if (data.status==="error"){
                            $("#info-messages").html(data.error_message)
                            return;
                        }

                        $("#btn-register").attr("disabled",true)
                        $("#info-messages").html(successMessageHtml("{{ _("Kaydınız başarıyla oluşturuldu.Giriş sayfasına yönlendiriliyorsunuz...") }}"));

                        setTimeout(function(){
                            window.location.href = "{{ url_for("auth.login") }}";
                        }, 2000);
                    }
                });
            }catch (e) {
                console.log(e);
            }

            return false;
        });


    })
    </script>

{% endblock %}